### ISSUE TITLE
Work without clients key files

### ISSUE THREAD

**Issue by pompushko** [alfiosalanitri/wireguard-client-connection-notification#8]
Hello

Is it possible to do anything to work without key files, if I havent any clients key public files :)?

Thank you

**Comment by alfiosalanitri** [comment]
Can you describe your setup so that I can emulate it? I will try to do so.

**Comment by alfiosalanitri** [comment]
The files inside /etc/wireguard/keys are used to identify the client_name so that when a connection or disconnection notification arrives, the name of who connected appears to you.

Here is an example of a file that you can create manually.

/etc/wireguard/keys/yoda_pub

Inside yoda_pub, you can put the public key that you get with: wg show wg0 dump | tail -n +2 | awk '{print $1}'. If this command returns multiple lines, it means you have multiple clients, and for each one, you need to create a file named clientname_pub.

In this way, you will receive the notification:

"The client yoda is...". Or "The client clientname is...". 

I will try soon to create an install.sh file that will ask for a name for each client during the installation of this script in order to automatically create the keys files.

**Comment by pompushko** [comment]
But what to do, if I have 100+ clients :D?

**Comment by alfiosalanitri** [comment]
To get the name of who connects or disconnects, you necessarily need to match the public key with the username.

Otherwise, you would only receive a generic notification and wouldn't know who did what.
And with 100+ clients, my script would be almost useless if you don't have a username.

**Comment by pompushko** [comment]
> To get the name of who connects or disconnects, you necessarily need to match the public key with the username.
> 
> Otherwise, you would only receive a generic notification and wouldn't know who did what. And with 100+ clients, my script would be almost useless if you don't have a username.

Why IP cannot be as username?

**Comment by alfiosalanitri** [comment]
Yes, of course, even the public key could be.

If you can distinguish the 100+ clients based on their IP (which could always change), you are either a genius or an artificial intelligence 😄

**Comment by pompushko** [comment]
> Yes, of course, even the public key could be.
> 
> If you can distinguish the 100+ clients based on their IP (which could always change), you are either a genius or an artificial intelligence 😄

Yep. I just need that :D
Dont ask me why :D

**Comment by alfiosalanitri** [comment]
I made the change, it should work. Let me know if there are any problems.

> > Yes, of course, even the public key could be.
> > If you can distinguish the 100+ clients based on their IP (which could always change), you are either a genius or an artificial intelligence 😄
> 
> Yep. I just need that :D Dont ask me why :D

I made the change, it should work. Let me know if there are any problems.
