### ISSUE TITLE
DNS IP instead of real IP

### ISSUE THREAD

**Issue by Cruncher13** [alfiosalanitri/wireguard-client-connection-notification#9]
In Telegram I get the DNS IP as "IP" instead of the real IP Address.

**Comment by alfiosalanitri** [comment]
The IP address shown by the `wg show wg0 dump` command might be a DNS IP instead of the client's real IP due to several reasons: 
- the client might be configured to use a specific DNS
- it could be behind a NAT or proxy
- the server might be set up to show the DNS IP for privacy

Try running that command in the terminal and see which IP it shows you.
